### ISSUE TITLE
Use home row keys by default instead of `abc`

### ISSUE THREAD

**Issue by hauleth** [yangmillstheory/vim-snipe#1]
This would be IMHO more useful. for touch typists.

**Comment by shelbyd** [comment]
Or, allow a custom list of keys that will be used in order.

So Qwerty users would set 'asdfjkl;'. And Colemak users (self included) can use 'arstneio'. And Dvorak users can do whatever they have. Of course people can use this however they want.

Probably should default to Qwerty home row keys.

**Comment by globalchubby** [comment]
Yes, this is something that's lacking. Actually there's no configurable options, I wanted to release something minimal for myself, hoping others would be interested enough to give feedback or contribute.

**Comment by rubdos** [comment]
> And Dvorak users can do whatever they have.

Checking in: aoeuhtns, thank you :-)
