### ISSUE TITLE
Add neovim support

### ISSUE THREAD

**Issue by chrhasse** [yangmillstheory/vim-snipe#20]
A couple issues prevent this from being compatible with neovim.

- neovim doesn't have `v:t_number`, using `type(0)` is the recommended alternative
- neovim doesn't allow empty keys in dictionaries (even though the [docs](https://neovim.io/doc/user/eval.html#Dictionary) say it's allowed). Naive fix is simply adding a space to the end of each key in `s:known_modes` and concatenating a space to the end of `a:mode`.

**Comment by globalchubby** [comment]
I'm surprised at the first point - I haven't had issues (even with targets mapped to multi-key sequences) and I'm using neovim? For the second, can we just test `a:mode ==# ''`?

Also, can you reference the lack of empty string key support in neovim? I'm curious since the docs say otherwise.

**Comment by chrhasse** [comment]
see comments in #21.
