### ISSUE TITLE
Document and allow configuration of highlighting format

### ISSUE THREAD

**Issue by globalchubby** [yangmillstheory/vim-snipe#3]

**Comment by jshort** [comment]
And doc for how to change the color of the highlighted characters please.

**Comment by jshort** [comment]
Right now I'm editing `~/.vim/pack/dist/start/vim-snipe/autoload/highlight.vim` directly to get the highlighting to work with my color scheme but a `vimrc` overridable config would be great!

**Comment by jshort** [comment]
I have a PR on the way fyi.
