### ISSUE TITLE
Using a motion should not alter the buffer's "modified" state

### ISSUE THREAD

**Issue by Vadskye** [yangmillstheory/vim-snipe#9]
Expected behavior: If I use a motion in an unmodified buffer, the buffer should still be considered unmodified after the motion is finished.

Current behavior: If I use a motion in an unmodified buffer, the buffer is considered to be "modified" after the motion is finished.

**Comment by globalchubby** [comment]
OK, this shouldn't apply to `snipe-*-x`, `snipe-*-xp`, `snipe-*-r`, since those write to the buffer, but everything else.

What are the consequences of the buffer being "modified"?

**Comment by Vadskye** [comment]
Ah, yes, thanks - this is only a bug when referring to the "motion-only" commands.

The main consequence I notice is that I get warnings when I try to close the buffer window (because Vim thinks I'm about to lose unsaved changes).

**Comment by globalchubby** [comment]
Thoughts on 19eb793?

**Comment by Vadskye** [comment]
LGTM
